project_id = "wimdgvdpefkmjzzsklnt"

[functions.travel-advisor-chat]
verify_jwt = false

[functions.send-admin-notification]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.extract-quote-pdf]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.send-checkin-notification]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false