import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, CalendarDays, Check, Compass, Gauge, Loader2, MessageCircle, Plane, Radar, Sparkles, Users, Wallet, WandSparkles } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { createMyRadar, type RadarInput } from "@/lib/myTomorrowRadars";

type Mode = "choose" | "visual" | "conversation" | "calibrate";
type Draft = { destination:string; origin:string; startDate:string; endDate:string; flexibility:number; passengers:number; budgetMax:string; category:string; priority:string; sensitivity:"observer"|"attentive"|"hunter"; };
const empty: Draft = { destination:"", origin:"", startDate:"", endDate:"", flexibility:7, passengers:2, budgetMax:"", category:"", priority:"", sensitivity:"attentive" };
const categories=["Praia","Neve","Parques","Natureza","Gastronomia","Cruzeiro","Resort","Cultura"];
const priorities=["Voo direto","Menor preço","Hotel bem localizado","All inclusive","Bagagem","Hotel 4★+","Datas flexíveis","Experiências incluídas"];
const origins=["GRU","CGH","VCP","Qualquer aeroporto de São Paulo"];
const budgetOptions=["2500","4000","6000","10000"];

function toIso(value:string){const m=value.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(!m)return "";return `${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`;}
function parseConversation(text:string,draft:Draft){const next={...draft};const upper=text.toUpperCase();const airport=upper.match(/\b(GRU|CGH|VCP)\b/);if(airport)next.origin=airport[1];const money=[...text.matchAll(/(?:R\$\s*)?([\d.]+)(?:,\d{2})?/gi)].map(m=>Number(m[1].replace(/\./g,""))).filter(n=>n>=500);if(money.length)next.budgetMax=String(Math.max(...money));const dates=[...text.matchAll(/\d{1,2}[\/-]\d{1,2}[\/-]\d{4}/g)].map(m=>toIso(m[0]));if(dates[0])next.startDate=dates[0];if(dates[1])next.endDate=dates[1];const pax=text.match(/(\d+)\s*(?:pessoas|passageiros|adultos)/i);if(pax)next.passengers=Math.max(1,Number(pax[1]));for(const category of categories){if(text.toLowerCase().includes(category.toLowerCase()))next.category=category.toLowerCase();}const destination=text.match(/(?:ir|viajar|quero ir|destino)\s+(?:para|pra|pro|a|ao)?\s*([A-ZÁÉÍÓÚÂÊÔÃÕÇ][\p{L}\s]{2,35}?)(?=\s+(?:em|entre|com|gastando|por|até)|[,.]|$)/iu);if(destination)next.destination=destination[1].trim();return next;}

export default function MyTomorrowRadarCreate(){const navigate=useNavigate();const[mode,setMode]=useState<Mode>("choose");const[step,setStep]=useState(0);const[draft,setDraft]=useState<Draft>(empty);const[text,setText]=useState("");const[saving,setSaving]=useState(false);const completion=useMemo(()=>{const signals=[draft.origin,draft.destination,draft.startDate,draft.endDate,draft.budgetMax,draft.category,draft.priority];return Math.round(30+signals.filter(Boolean).length/7*65);},[draft]);
const set=<K extends keyof Draft>(key:K,value:Draft[K])=>setDraft(current=>({...current,[key]:value}));
const create=async()=>{setSaving(true);try{const name=`Radar ${draft.destination||draft.category||"Tomorrow"}`;const input:RadarInput={name,origin:draft.origin.startsWith("Qualquer")?null:draft.origin||null,destination:draft.destination||null,start_date:draft.startDate||null,end_date:draft.endDate||null,flexibility_days:draft.flexibility,passengers:draft.passengers,budget_max:draft.budgetMax?Number(draft.budgetMax):undefined,category:draft.category||null,source:"manual",source_filters:{builder:"immersive-v1",priority:draft.priority||null,sensitivity:draft.sensitivity,origin_scope:draft.origin.startsWith("Qualquer")?"sao_paulo_airports":null}};const radar=await createMyRadar(input);navigate(`/minha-area/radares/${radar.id}`);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível ativar o Radar.");}finally{setSaving(false);}};
const goCalibrate=()=>setMode("calibrate");
if(mode==="choose")return <Shell><div className="mx-auto max-w-3xl text-center"><div className="mx-auto grid size-20 place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/[.06] shadow-[0_0_60px_rgba(34,211,238,.12)]"><Radar className="size-9 text-cyan-300"/></div><p className="mt-7 text-xs font-semibold uppercase tracking-[.28em] text-cyan-300">Novo Radar Tomorrow</p><h1 className="mt-3 font-serif text-4xl sm:text-6xl">Como você quer calibrar seu Radar?</h1><p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-white/50">Sem formulário. Você pode contar o que procura ou montar visualmente, decisão por decisão.</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><ModeCard icon={<MessageCircle/>} title="Quero contar" text="Descreva sua viagem como falaria com um consultor. O Radar organiza os sinais e pede apenas o que faltar." onClick={()=>setMode("conversation")}/><ModeCard icon={<WandSparkles/>} title="Quero montar" text="Uma experiência visual para escolher destino, período, orçamento e o que realmente faria você embarcar." onClick={()=>setMode("visual")}/></div></div></Shell>;
if(mode==="conversation")return <Shell><Top back={()=>setMode("choose")} label="Radar por conversa" progress={completion}/><div className="mx-auto mt-8 max-w-2xl"><div className="rounded-[2rem] border border-cyan-300/15 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.10),transparent_38%),#07191c] p-6"><div className="flex gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-full bg-cyan-300/10"><Radar className="size-5 text-cyan-300"/></div><div><p className="text-sm font-semibold">O que você está esperando aparecer?</p><p className="mt-1 text-sm text-white/50">Pode escrever destino, datas, quem vai e quanto pretende investir. Não precisa preencher tudo.</p></div></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Ex.: Quero ir para Beto Carrero entre 10/10/2026 e 20/10/2026, saindo de GRU, 3 passageiros e até R$ 4.000 por pessoa." className="mt-6 min-h-36 w-full resize-none rounded-2xl border border-white/10 bg-black/20 p-4 text-base outline-none focus:border-cyan-300/40"/><button onClick={()=>{const parsed=parseConversation(text,draft);setDraft(parsed);setStep(1);}} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-[#041012]">Ler minha intenção <Sparkles className="size-4"/></button></div>{step>0?<SignalReview draft={draft} setValue={set} onContinue={goCalibrate}/>:null}</div></Shell>;
if(mode==="visual")return <Shell><Top back={()=>step?setStep(step-1):setMode("choose")} label="Calibrando Radar" progress={Math.round((step+1)/6*100)}/><div className="mx-auto mt-8 max-w-3xl">{step===0?<ChoiceStep eyebrow="Primeiro sinal" title="De onde você quer embarcar?" options={origins} value={draft.origin} onPick={v=>{set("origin",v);setStep(1);}}/>:null}{step===1?<TextStep title="Para onde seu Radar deve olhar?" placeholder="Ex.: Beto Carrero, Orlando, Lisboa..." value={draft.destination} onChange={v=>set("destination",v)} chips={categories} onChip={v=>set("category",v.toLowerCase())} onNext={()=>setStep(2)}/>:null}{step===2?<DateStep draft={draft} setValue={set} onNext={()=>setStep(3)}/>:null}{step===3?<ChoiceStep eyebrow="Investimento" title="Até quanto faria sentido por pessoa?" options={budgetOptions.map(v=>`Até R$ ${Number(v).toLocaleString("pt-BR")}`)} value={draft.budgetMax?`Até R$ ${Number(draft.budgetMax).toLocaleString("pt-BR")}`:""} onPick={v=>{const raw=v.replace(/\D/g,"");set("budgetMax",raw);setStep(4);}}/>:null}{step===4?<ChoiceStep eyebrow="Sinal decisivo" title="O que faria você embarcar?" options={priorities} value={draft.priority} onPick={v=>{set("priority",v);setStep(5);}}/>:null}{step===5?<Sensitivity value={draft.sensitivity} onPick={v=>{set("sensitivity",v);goCalibrate();}}/>:null}</div></Shell>;
return <Shell><Top back={()=>setMode("visual")} label="Radar calibrado" progress={completion}/><div className="mx-auto mt-8 max-w-2xl text-center"><div className="relative mx-auto grid size-52 place-items-center rounded-full border border-cyan-300/20"><div className="absolute inset-5 rounded-full border border-cyan-300/10"/><div className="absolute inset-12 rounded-full border border-[#d4af37]/20"/><Radar className="size-16 text-cyan-300"/><span className="absolute bottom-7 text-xs uppercase tracking-[.2em] text-white/40">{completion}% calibrado</span></div><h1 className="mt-7 font-serif text-4xl">{`Radar ${draft.destination||draft.category||"Tomorrow"}`}</h1><div className="mt-7 grid gap-3 text-left sm:grid-cols-2"><Summary label="Origem" value={draft.origin||"Aberta"}/><Summary label="Destino" value={draft.destination||draft.category||"Discovery aberto"}/><Summary label="Período" value={draft.startDate&&draft.endDate?`${draft.startDate} → ${draft.endDate}`:"Aberto"}/><Summary label="Flexibilidade" value={`±${draft.flexibility} dias`}/><Summary label="Investimento" value={draft.budgetMax?`Até R$ ${Number(draft.budgetMax).toLocaleString("pt-BR")}/pessoa`:"Aberto"}/><Summary label="Radar" value={draft.sensitivity==="hunter"?"Caçador":draft.sensitivity==="observer"?"Observador":"Atento"}/></div><button disabled={saving} onClick={()=>void create()} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-6 py-4 font-semibold text-[#041012] disabled:opacity-50">{saving?<Loader2 className="size-5 animate-spin"/>:<Gauge className="size-5"/>}{saving?"Ativando...":"Ativar meu Radar"}</button></div></Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[radial-gradient(circle_at_50%_-10%,rgba(20,184,196,.12),transparent_32%),#041012] px-4 pb-16 pt-8 text-white">{children}</main>}
function Top({back,label,progress}:{back:()=>void;label:string;progress:number}){return <div className="mx-auto flex max-w-3xl items-center gap-4"><button onClick={back} className="grid size-11 place-items-center rounded-full border border-white/10"><ArrowLeft className="size-4"/></button><div className="flex-1"><div className="flex justify-between text-[11px] uppercase tracking-[.18em] text-white/45"><span>{label}</span><span>{progress}%</span></div><div className="mt-2 h-1 rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300 transition-all" style={{width:`${progress}%`}}/></div></div></div></div>}
function ModeCard({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className="group rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-left transition hover:border-cyan-300/30 hover:bg-cyan-300/[.04]"><div className="grid size-14 place-items-center rounded-2xl border border-[#d4af37]/25 text-[#e8c95d]">{icon}</div><h2 className="mt-6 font-serif text-3xl">{title}</h2><p className="mt-3 text-sm leading-relaxed text-white/50">{text}</p><ArrowRight className="mt-6 size-5 text-cyan-300 transition group-hover:translate-x-1"/></button>}
function ChoiceStep({eyebrow,title,options,value,onPick}:{eyebrow:string;title:string;options:string[];value:string;onPick:(v:string)=>void}){return <div><p className="text-xs uppercase tracking-[.2em] text-cyan-300">{eyebrow}</p><h1 className="mt-3 font-serif text-4xl">{title}</h1><div className="mt-8 grid gap-3 sm:grid-cols-2">{options.map(o=><button key={o} onClick={()=>onPick(o)} className={`rounded-2xl border p-5 text-left text-sm transition ${value===o?"border-cyan-300 bg-cyan-300/10":"border-white/10 bg-white/[.03]"}`}>{o}</button>)}</div></div>}
function TextStep({title,placeholder,value,onChange,chips,onChip,onNext}:{title:string;placeholder:string;value:string;onChange:(v:string)=>void;chips:string[];onChip:(v:string)=>void;onNext:()=>void}){return <div><h1 className="font-serif text-4xl">{title}</h1><input autoFocus value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-7 w-full rounded-2xl border border-white/10 bg-white/[.03] p-5 text-lg outline-none focus:border-cyan-300/40"/><p className="mt-6 text-xs uppercase tracking-[.16em] text-white/35">Ou deixe o Radar descobrir por experiência</p><div className="mt-3 flex flex-wrap gap-2">{chips.map(c=><button key={c} onClick={()=>onChip(c)} className="rounded-full border border-white/10 px-4 py-2 text-sm text-white/65">{c}</button>)}</div><Next onClick={onNext}/></div>}
function DateStep({draft,setValue,onNext}:{draft:Draft;setValue:<K extends keyof