import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Gauge, Loader2, MessageCircle, Radar, Sparkles, WandSparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { createMyRadar, type RadarInput } from "@/lib/myTomorrowRadars";

type Mode="choose"|"visual"|"conversation"|"calibrate";
type Draft={destination:string;origin:string;startDate:string;endDate:string;flexibility:number;passengers:number;budgetMax:string;category:string;priority:string;sensitivity:"observer"|"attentive"|"hunter"};
const initial:Draft={destination:"",origin:"",startDate:"",endDate:"",flexibility:7,passengers:2,budgetMax:"",category:"",priority:"",sensitivity:"attentive"};
const categories=["Praia","Neve","Parques","Natureza","Gastronomia","Cruzeiro","Resort","Cultura"];
const priorities=["Voo direto","Menor preço","Hotel bem localizado","All inclusive","Bagagem","Hotel 4★+","Datas flexíveis","Experiências incluídas"];
const origins=["GRU","CGH","VCP","Qualquer aeroporto de São Paulo"];
const budgets=[2500,4000,6000,10000];
function iso(v:string){const m=v.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:""}
function parse(text:string,d:Draft){const n={...d},up=text.toUpperCase(),a=up.match(/\b(GRU|CGH|VCP)\b/);if(a)n.origin=a[1];const dates=[...text.matchAll(/\d{1,2}[\/-]\d{1,2}[\/-]\d{4}/g)].map(x=>iso(x[0]));if(dates[0])n.startDate=dates[0];if(dates[1])n.endDate=dates[1];const money=[...text.matchAll(/R\$\s*([\d.]+)/gi)].map(x=>Number(x[1].replace(/\./g,"")));if(money.length)n.budgetMax=String(Math.max(...money));const pax=text.match(/(\d+)\s*(?:pessoas|passageiros|adultos)/i);if(pax)n.passengers=Number(pax[1]);for(const c of categories)if(text.toLowerCase().includes(c.toLowerCase()))n.category=c.toLowerCase();const dest=text.match(/(?:ir|viajar)\s+(?:para|pra|pro|a|ao)?\s*([\p{L}\s]{3,30}?)(?=\s+(?:em|entre|com|gastando|até)|[,.]|$)/iu);if(dest)n.destination=dest[1].trim();return n}
export default function MyTomorrowRadarCreate(){const nav=useNavigate();const[mode,setMode]=useState<Mode>("choose");const[step,setStep]=useState(0);const[d,setD]=useState(initial);const[text,setText]=useState("");const[saving,setSaving]=useState(false);const set=<K extends keyof Draft>(k:K,v:Draft[K])=>setD(x=>({...x,[k]:v}));const completion=useMemo(()=>Math.round(30+[d.origin,d.destination,d.startDate,d.endDate,d.budgetMax,d.category,d.priority].filter(Boolean).length/7*65),[d]);
const activate=async()=>{setSaving(true);try{const input:RadarInput={name:`Radar ${d.destination||d.category||"Tomorrow"}`,origin:d.origin.startsWith("Qualquer")?null:d.origin||null,destination:d.destination||null,start_date:d.startDate||null,end_date:d.endDate||null,flexibility_days:d.flexibility,passengers:d.passengers,budget_max:d.budgetMax?Number(d.budgetMax):undefined,category:d.category||null,source:"manual",source_filters:{builder:"immersive-v1",priority:d.priority||null,sensitivity:d.sensitivity,origin_scope:d.origin.startsWith("Qualquer")?"sao_paulo_airports":null}};const radar=await createMyRadar(input);nav(`/minha-area/radares/${radar.id}`)}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível ativar o Radar.")}finally{setSaving(false)}};
if(mode==="choose")return <Shell><div className="mx-auto max-w-3xl text-center"><RadarOrb/><p className="mt-7 text-xs font-semibold uppercase tracking-[.28em] text-cyan-300">Novo Radar Tomorrow</p><h1 className="mt-3 font-serif text-4xl sm:text-6xl">Como você quer calibrar seu Radar?</h1><p className="mx-auto mt-4 max-w-xl text-sm text-white/50">Sem formulário. Conte o que procura ou monte visualmente, decisão por decisão.</p><div className="mt-10 grid gap-4 sm:grid-cols-2"><ModeCard icon={<MessageCircle/>} title="Quero contar" text="Fale como falaria com um consultor. O Radar organiza os sinais e mostra o que entendeu." onClick={()=>setMode("conversation")}/><ModeCard icon={<WandSparkles/>} title="Quero montar" text="Escolha visualmente origem, destino, período, orçamento e o que faria você embarcar." onClick={()=>setMode("visual")}/></div></div></Shell>;
if(mode==="conversation")return <Shell><Top back={()=>setMode("choose")} label="Radar por conversa" progress={completion}/><div className="mx-auto mt-8 max-w-2xl"><Panel><p className="text-sm font-semibold">O que você está esperando aparecer?</p><p className="mt-2 text-sm text-white/50">Escreva naturalmente. Ex.: “Quero ir para Beto Carrero entre 10/10/2026 e 20/10/2026, saindo de GRU, 3 passageiros e até R$ 4.000 por pessoa.”</p><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-5 min-h-36 w-full resize-none rounded-2xl border border-white/10 bg-black/20 p-4 outline-none focus:border-cyan-300/40"/><button onClick={()=>{setD(parse(text,d));setStep(1)}} className="mt-4 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-[#041012]">Ler minha intenção</button></Panel>{step>0?<div className="mt-5"><h2 className="font-serif text-2xl">Foi isso que eu entendi</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="Origem" value={d.origin} onChange={v=>set("origin",v)}/><Field label="Destino" value={d.destination} onChange={v=>set("destination",v)}/><Field label="Data inicial" value={d.startDate} type="date" onChange={v=>set("startDate",v)}/><Field label="Data final" value={d.endDate} type="date" onChange={v=>set("endDate",v)}/><Field label="Passageiros" value={String(d.passengers)} type="number" onChange={v=>set("passengers",Number(v)||1)}/><Field label="Até R$ por pessoa" value={d.budgetMax} type="number" onChange={v=>set("budgetMax",v)}/></div><Next onClick={()=>setMode("calibrate")} text="Calibrar Radar"/></div>:null}</div></Shell>;
if(mode==="visual")return <Shell><Top back={()=>step?setStep(step-1):setMode("choose")} label="Calibrando Radar" progress={Math.round((step+1)/6*100)}/><div className="mx-auto mt-8 max-w-3xl">{step===0?<Choices title="De onde você quer embarcar?" options={origins} onPick={v=>{set("origin",v);setStep(1)}}/>:null}{step===1?<div><h1 className="font-serif text-4xl">Para onde seu Radar deve olhar?</h1><input value={d.destination} onChange={e=>set("destination",e.target.value)} placeholder="Beto Carrero, Orlando, Lisboa..." className="mt-7 w-full rounded-2xl border border-white/10 bg-white/[.03] p-5 text-lg outline-none"/><p className="mt-6 text-xs uppercase tracking-[.16em] text-white/35">Ou descubra por experiência</p><div className="mt-3 flex flex-wrap gap-2">{categories.map(c=><button key={c} onClick={()=>set("category",c.toLowerCase())} className={`rounded-full border px-4 py-2 text-sm ${d.category===c.toLowerCase()?"border-cyan-300 text-cyan-200":"border-white/10 text-white/60"}`}>{c}</button>)}</div><Next onClick={()=>setStep(2)}/></div>:null}{step===2?<div><h1 className="font-serif text-4xl">Quando você consegue viajar?</h1><div className="mt-7 grid gap-3 sm:grid-cols-2"><Field label="De" value={d.startDate} type="date" onChange={v=>set("startDate",v)}/><Field label="Até" value={d.endDate} type="date" onChange={v=>set("endDate",v)}/></div><p className="mt-6 text-xs uppercase tracking-[.16em] text-white/35">Flexibilidade</p><div className="mt-3 flex gap-2">{[0,7,15,30].map(x=><button key={x} onClick={()=>set("flexibility",x)} className={`rounded-xl border px-4 py-3 text-sm ${d.flexibility===x?"border-cyan-300 bg-cyan-300/10":"border-white/10"}`}>{x?`±${x} dias`:"Datas exatas"}</button>)}</div><Next onClick={()=>setStep(3)}/></div>:null}{step===3?<Choices title="Até quanto faria sentido por pessoa?" options={budgets.map(v=>`Até R$ ${v.toLocaleString("pt-BR")}`)} onPick={v=>{set("budgetMax",v.replace(/\D/g,""));setStep(4)}}/>:null}{step===4?<Choices title="O que faria você embarcar?" options={priorities} onPick={v=>{set("priority",v);setStep(5)}}/>:null}{step===5?<Choices title="Quão agressivo deve ser o Radar?" options={["Observador — só fora da curva","Atento — boas oportunidades","Caçador — quero saber rápido"]} onPick={v=>{set("sensitivity",v.startsWith("Observador")?"observer":v.startsWith("Caçador")?"hunter":"attentive");setMode("calibrate")}}/>:null}</div></Shell>;
return <Shell><Top back={()=>setMode("visual")} label="Radar calibrado" progress={completion}/><div className="mx-auto mt-8 max-w-2xl text-center"><RadarOrb large/><h1 className="mt-7 font-serif text-4xl">Radar {d.destination||d.category||"Tomorrow"}</h1><p className="mt-2 text-sm text-white/45">{completion}% calibrado · pronto para começar a procurar sinais</p><div className="mt-7 grid gap-3 text-left sm:grid-cols-2"><Summary label="Origem" value={d.origin||"Aberta"}/><Summary label="Destino" value={d.destination||d.category||"Discovery aberto"}/><Summary label="Período" value={d.startDate&&d.endDate?`${d.startDate} → ${d.endDate}`:"Aberto"}/><Summary label="Flexibilidade" value={`±${d.flexibility} dias`}/><Summary label="Investimento" value={d.budgetMax?`Até R$ ${Number(d.budgetMax).toLocaleString("pt-BR")}/pessoa`:"Aberto"}/><Summary label="Sensibilidade" value={d.sensitivity==="hunter"?"Caçador":d.sensitivity==="observer"?"Observador":"Atento"}/></div><button disabled={saving} onClick={()=>void activate()} className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-cyan-300 px-6 py-4 font-semibold text-[#041012] disabled:opacity-50">{saving?<Loader2 className="size-5 animate-spin"/>:<Gauge className="size-5"/>}{saving?"Ativando...":"Ativar meu Radar"}</button></div></Shell>}
function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[radial-gradient(circle_at_50%_-10%,rgba(20,184,196,.12),transparent_32%),#041012] px-4 pb-16 pt-8 text-white">{children}</main>}
function RadarOrb({large=false}:{large?:boolean}){return <div className={`relative mx-auto grid place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/[.04] ${large?"size-52":"size-20"}`}><div className="absolute inset-[18%] rounded-full border border-[#d4af37]/20"/><Radar className={`${large?"size-16":"size-9"} text-cyan-300`}/></div>}
function Top({back,label,progress}:{back:()=>void;label:string;progress:number}){return <div className="mx-auto flex max-w-3xl items-center gap-4"><button onClick={back} className="grid size-11 place-items-center rounded-full border border-white/10"><ArrowLeft className="size-4"/></button><div className="flex-1"><div className="flex justify-between text-[11px] uppercase tracking-[.18em] text-white/45"><span>{label}</span><span>{progress}%</span></div><div className="mt-2 h-1 rounded-full bg-white/10"><div className="h-full rounded-full bg-cyan-300" style={{width:`${progress}%`}}/></div></div></div>}
function ModeCard({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className="group rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-left"><div className="grid size-14 place-items-center rounded-2xl border border-[#d4af37]/25 text-[#e8c95d]">{icon}</div><h2 className="mt-6 font-serif text-3xl">{title}</h2><p className="mt-3 text-sm leading-relaxed text-white/50">{text}</p><ArrowRight className="mt-6 size-5 text-cyan-300"/></button>}
function Panel({children}:{children:React.ReactNode}){return <div className="rounded-[2rem] border border-cyan-300/15 bg-[#07191c] p-6">{children}</div>}
function Choices({title,options,onPick}:{title:string;options:string[];onPick:(v:string)=>void}){return <div><h1 className="font-serif text-4xl">{title}</h1><div className="mt-8 grid gap-3 sm:grid-cols-2">{options.map(o=><button key={o} onClick={()=>onPick(o)} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 text-left text-sm hover:border-cyan-300/30">{o}</button>)}</div></div>}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left"><span className="text-[11px] uppercase tracking-[.14em] text-white/35">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-2 w-full bg-transparent text-sm outline-none"/></label>}
function Next({onClick,text="Continuar"}:{onClick:()=>void;text?:string}){return <button onClick={onClick} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-semibold text-[#041