import { useMemo,useState } from "react";
import { ArrowLeft,ArrowRight,Loader2,MessageCircle,Radar,WandSparkles } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { createMyRadar,type RadarInput } from "@/lib/myTomorrowRadars";
type Mode="choose"|"visual"|"talk"|"done"; type D={origin:string;destination:string;start:string;end:string;flex:number;pax:number;budget:string;category:string;priority:string;sensitivity:string};
const base:D={origin:"",destination:"",start:"",end:"",flex:7,pax:2,budget:"",category:"",priority:"",sensitivity:"attentive"};
const cats=["Praia","Neve","Parques","Natureza","Gastronomia","Cruzeiro","Resort","Cultura"],origins=["GRU","CGH","VCP","Qualquer aeroporto de São Paulo"],priorities=["Voo direto","Menor preço","Hotel bem localizado","All inclusive","Bagagem","Hotel 4★+","Datas flexíveis","Experiências incluídas"];
function parse(t:string,d:D){const n={...d},a=t.toUpperCase().match(/\b(GRU|CGH|VCP)\b/);if(a)n.origin=a[1];const ds=[...t.matchAll(/(\d{1,2})[/-](\d{1,2})[/-](\d{4})/g)].map(x=>`${x[3]}-${x[2].padStart(2,"0")}-${x[1].padStart(2,"0")}`);n.start=ds[0]||n.start;n.end=ds[1]||n.end;const m=t.match(/R\$\s*([\d.]+)/i);if(m)n.budget=m[1].replace(/\./g,"");const p=t.match(/(\d+)\s*(?:pessoas|passageiros|adultos)/i);if(p)n.pax=Number(p[1]);for(const c of cats)if(t.toLowerCase().includes(c.toLowerCase()))n.category=c.toLowerCase();const dest=t.match(/(?:ir|viajar)\s+(?:para|pra|pro|a|ao)?\s*([\p{L}\s]{3,30}?)(?=\s+(?:em|entre|com|até)|[,.]|$)/iu);if(dest)n.destination=dest[1].trim();return n}
export default function MyTomorrowRadarCreate(){const nav=useNavigate();const[mode,setMode]=useState<Mode>("choose");const[step,setStep]=useState(0);const[d,setD]=useState(base);const[text,setText]=useState("");const[saving,setSaving]=useState(false);const set=(k:keyof D,v:string|number)=>setD(x=>({...x,[k]:v}));const pct=useMemo(()=>30+Math.round([d.origin,d.destination,d.start,d.end,d.budget,d.category,d.priority].filter(Boolean).length/7*65),[d]);
const activate=async()=>{setSaving(true);try{const input:RadarInput={name:`Radar ${d.destination||d.category||"Tomorrow"}`,origin:d.origin.startsWith("Qualquer")?null:d.origin||null,destination:d.destination||null,start_date:d.start||null,end_date:d.end||null,flexibility_days:d.flex,passengers:d.pax,budget_max:d.budget?Number(d.budget):undefined,category:d.category||null,source:"manual",source_filters:{builder:"immersive-v1",priority:d.priority||null,sensitivity:d.sensitivity,origin_scope:d.origin.startsWith("Qualquer")?"sao_paulo_airports":null}};const r=await createMyRadar(input);nav(`/minha-area/radares/${r.id}`)}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível ativar o Radar.")}finally{setSaving(false)}};
return <main className="min-h-screen bg-[radial-gradient(circle_at_top,rgba(34,211,238,.10),transparent_30%),#041012] px-4 py-8 text-white">{mode==="choose"?<section className="mx-auto max-w-3xl pt-10 text-center"><Orb/><p className="mt-6 text-xs uppercase tracking-[.25em] text-cyan-300">Novo Radar Tomorrow</p><h1 className="mt-3 font-serif text-4xl sm:text-6xl">Como você quer calibrar?</h1><p className="mx-auto mt-4 max-w-xl text-sm text-white/50">Sem formulário. Conte o que procura ou construa visualmente.</p><div className="mt-9 grid gap-4 sm:grid-cols-2"><Mode icon={<MessageCircle/>} title="Quero contar" text="Descreva a viagem naturalmente e revise apenas os sinais que o Radar captou." onClick={()=>setMode("talk")}/><Mode icon={<WandSparkles/>} title="Quero montar" text="Uma sequência visual de decisões rápidas, sem uma parede de campos." onClick={()=>setMode("visual")}/></div></section>:null}
{mode==="talk"?<section className="mx-auto max-w-2xl"><Top back={()=>setMode("choose")} title="Radar por conversa" pct={pct}/><div className="mt-8 rounded-[2rem] border border-cyan-300/15 bg-white/[.035] p-6"><h2 className="font-serif text-2xl">O que você está esperando aparecer?</h2><p className="mt-2 text-sm text-white/45">Ex.: Quero ir para Beto Carrero entre 10/10/2026 e 20/10/2026, saindo de GRU, 3 passageiros e até R$ 4.000.</p><textarea value={text} onChange={e=>setText(e.target.value)} className="mt-5 min-h-36 w-full rounded-2xl border border-white/10 bg-black/20 p-4 outline-none"/><button onClick={()=>{setD(parse(text,d));setStep(1)}} className="mt-4 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-[#041012]">Interpretar intenção</button></div>{step?<><h3 className="mt-7 font-serif text-2xl">Foi isso que eu entendi</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field l="Origem" v={d.origin} set={v=>set("origin",v)}/><Field l="Destino" v={d.destination} set={v=>set("destination",v)}/><Field l="De" v={d.start} type="date" set={v=>set("start",v)}/><Field l="Até" v={d.end} type="date" set={v=>set("end",v)}/><Field l="Passageiros" v={String(d.pax)} type="number" set={v=>set("pax",Number(v)||1)}/><Field l="Até R$ / pessoa" v={d.budget} type="number" set={v=>set("budget",v)}/></div><Next onClick={()=>setMode("done")}/></>:null}</section>:null}
{mode==="visual"?<section className="mx-auto max-w-3xl"><Top back={()=>step?setStep(step-1):setMode("choose")} title="Calibrando Radar" pct={Math.round((step+1)/6*100)}/><div className="mt-9">{step===0?<Choices title="De onde você quer embarcar?" items={origins} pick={v=>{set("origin",v);setStep(1)}}/>:null}{step===1?<><h2 className="font-serif text-4xl">Para onde seu Radar deve olhar?</h2><Field l="Destino" v={d.destination} set={v=>set("destination",v)}/><p className="mt-6 text-xs uppercase tracking-widest text-white/35">Ou descubra por experiência</p><div className="mt-3 flex flex-wrap gap-2">{cats.map(c=><button key={c} onClick={()=>set("category",c.toLowerCase())} className="rounded-full border border-white/10 px-4 py-2 text-sm">{c}</button>)}</div><Next onClick={()=>setStep(2)}/></>:null}{step===2?<><h2 className="font-serif text-4xl">Quando você consegue viajar?</h2><div className="mt-6 grid gap-3 sm:grid-cols-2"><Field l="De" v={d.start} type="date" set={v=>set("start",v)}/><Field l="Até" v={d.end} type="date" set={v=>set("end",v)}/></div><div className="mt-4 flex flex-wrap gap-2">{[0,7,15,30].map(x=><button key={x} onClick={()=>set("flex",x)} className={`rounded-xl border px-4 py-3 text-sm ${d.flex===x?"border-cyan-300":"border-white/10"}`}>{x?`±${x} dias`:"Datas exatas"}</button>)}</div><Next onClick={()=>setStep(3)}/></>:null}{step===3?<Choices title="Até quanto faria sentido por pessoa?" items={[2500,4000,6000,10000].map(x=>`Até R$ ${x.toLocaleString("pt-BR")}`)} pick={v=>{set("budget",v.replace(/\D/g,""));setStep(4)}}/>:null}{step===4?<Choices title="O que faria você embarcar?" items={priorities} pick={v=>{set("priority",v);setStep(5)}}/>:null}{step===5?<Choices title="Quão agressivo deve ser o Radar?" items={["Observador — só fora da curva","Atento — boas oportunidades","Caçador — quero saber rápido"]} pick={v=>{set("sensitivity",v.startsWith("Caçador")?"hunter":v.startsWith("Observador")?"observer":"attentive");setMode("done")}}/>:null}</div></section>:null}
{mode==="done"?<section className="mx-auto max-w-2xl text-center"><Top back={()=>setMode("visual")} title="Radar calibrado" pct={pct}/><div className="mt-9"><Orb big/><h2 className="mt-6 font-serif text-4xl">Radar {d.destination||d.category||"Tomorrow"}</h2><p className="mt-2 text-sm text-white/45">{pct}% calibrado · pronto para procurar sinais</p><div className="mt-7 grid gap-3 text-left sm:grid-cols-2"><Sum l="Origem" v={d.origin||"Aberta"}/><Sum l="Destino" v={d.destination||d.category||"Discovery aberto"}/><Sum l="Período" v={d.start&&d.end?`${d.start} → ${d.end}`:"Aberto"}/><Sum l="Flexibilidade" v={`±${d.flex} dias`}/><Sum l="Investimento" v={d.budget?`Até R$ ${Number(d.budget).toLocaleString("pt-BR")}/pessoa`:"Aberto"}/><Sum l="Sensibilidade" v={d.sensitivity}/></div><button disabled={saving} onClick={()=>void activate()} className="mt-8 w-full rounded-2xl bg-cyan-300 px-6 py-4 font-semibold text-[#041012]">{saving?<Loader2 className="mx-auto size-5 animate-spin"/>:"Ativar meu Radar"}</button></div></section>:null}</main>}
function Orb({big=false}:{big?:boolean}){return <div className={`relative mx-auto grid place-items-center rounded-full border border-cyan-300/20 bg-cyan-300/[.04] ${big?"size-48":"size-20"}`}><div className="absolute inset-[20%] rounded-full border border-[#d4af37]/25"/><Radar className={`${big?"size-14":"size-9"} text-cyan-300`}/></div>}
function Top({back,title,pct}:{back:()=>void;title:string;pct:number}){return <div className="flex items-center gap-4"><button onClick={back} className="grid size-10 place-items-center rounded-full border border-white/10"><ArrowLeft className="size-4"/></button><div className="flex-1"><div className="flex justify-between text-xs uppercase tracking-widest text-white/40"><span>{title}</span><span>{pct}%</span></div><div className="mt-2 h-1 bg-white/10"><div className="h-full bg-cyan-300" style={{width:`${pct}%`}}/></div></div></div>}
function Mode({icon,title,text,onClick}:{icon:React.ReactNode;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className="rounded-[2rem] border border-white/10 bg-white/[.035] p-7 text-left"><div className="text-[#e8c95d]">{icon}</div><h2 className="mt-5 font-serif text-3xl">{title}</h2><p className="mt-3 text-sm text-white/50">{text}</p><ArrowRight className="mt-5 size-5 text-cyan-300"/></button>}
function Choices({title,items,pick}:{title:string;items:string[];pick:(v:string)=>void}){return <><h2 className="font-serif text-4xl">{title}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{items.map(x=><button key={x} onClick={()=>pick(x)} className="rounded-2xl border border-white/10 bg-white/[.03] p-5 text-left text-sm hover:border-cyan-300/30">{x}</button>)}</div></>}
function Field({l,v,set,type="text"}:{l:string;v:string;set:(v:string)=>void;type?:string}){return <label className="mt-3 block rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left"><span className="text-xs text-white/35">{l}</span><input type={type} value={v} onChange={e=>set(e.target.value)} className="mt-1 w-full bg-transparent outline-none"/></label>}
function Next({onClick}:{onClick:()=>void}){return <button onClick={onClick} className="mt-7 rounded-xl bg-cyan-300 px-5 py-3 font-semibold text-[#041012]">Continuar</button>}
function Sum({l,v}:{l:string;v:string}){return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-xs uppercase tracking-widest text-white/30">{l}</p><p className="mt-2 text-sm">{v}</p></div>}
